- terraform/aws/README.md
> doc: Update README.md

- .github/renovate.json5
Fixes https://github.com/cloudquery/helm-charts/issues/45. Still need to test this
> chore: Update cloudquery in chart

- .gitignore
- kind-config.yaml
- scripts/e2e-kind.sh
> feat: Add kind testing prerequisites

- .github/workflows/bump_versions.yml
Follow up to https://github.com/cloudquery/helm-charts/pull/94
> chore(ci): Pass branch name to git-auto-commit-action

- .github/workflows/manual_triggers.yml
Adds a debug log for testing purposes. I'll remove in a bit
> chore: Add debug log

- .github/.kodiak.toml
- .github/renovate.json5
Should be handled via https://github.com/cloudquery/.github/pull/350
> chore: Remove Kodiak automerge in favor of renvoate

- .github/workflows/issue_to_project.yml
Same as https://github.com/cloudquery/cloudquery/pull/2693
> chore: Add Issue to public roadmap project

- .github/workflows/deps_bump_versions.yml
Automates https://github.com/cloudquery/helm-charts/pull/131#issuecomment-1282405110
> chore: Auto bump versions and docs for dep updates

- .github/renovate.json5
Replaced by https://github.com/cloudquery/.github/pull/359
> chore: Update renovate

- .github/renovate.json5
Goes with https://github.com/cloudquery/.github/pull/369
> chore(deps): Set cloudquery updates to fix type

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/values.yaml
`v7.3.1` of the AWS plugin is broken
> fix: Revert AWS plugin update

- .github/renovate.json5
Similar to https://github.com/cloudquery/.github/pull/382
> chore: Fix renovate patterns

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/admin-deployment.yaml
- charts/cloudquery/templates/cronjob.yaml
- charts/cloudquery/values.yaml
Hi,
this adds the requested feature in #260 and #261.
Not sure if anything else needs to be done, never contributed to any other project yet.
Feel free to make adjustments.
Cheers,
@cberge908
> feat: Add nodeSelector and dedicated resource quota admin pod/ cronJob 

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/job.yaml
- charts/cloudquery/values.yaml
> feat: Add an option to create a job that runs once upon installation

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/job.yaml
Fix volume and volumeMounts indentation on job.yaml
> fix: Job volume and volumeMounts indentation

- .github/workflows/release_please.yml
- .release-please-manifest.json
- release-please-config.json
Adds release-please to manage platform helm chart releases.
> chore: Adding release-please for platform helm chart

- release-please-config.json
To address failing check in https://github.com/cloudquery/helm-charts/pull/457
> chore: Change the PR title to satisfy the PR title workflow

- .release-please-manifest.json
- release-please-config.json
> chore: Individual release PRs

- .release-please-manifest.json
- charts/cloudquery/README.md
- charts/platform/CHANGELOG.md
- charts/platform/Chart.yaml
- charts/platform/README.md
Reverts cloudquery/helm-charts#478
> chore: Revert "chore(main): Release platform 0.1.2"

- charts/platform/Chart.yaml
- charts/platform/README.md
- charts/platform/README.md.gotmpl
- charts/platform/ci/test-values.yaml
- charts/platform/templates/NOTES.txt
- charts/platform/templates/_helpers.tpl
- charts/platform/templates/deployments.yaml
- charts/platform/templates/ingress.yaml
- charts/platform/templates/secrets.yaml
- charts/platform/templates/services.yaml
- charts/platform/values.yaml
- **Remove `platform` root element**
- **Point to single proxy port `3000`**
- **Adding ingress**
> feat: Adding platform ingress

- .github/workflows/release_please.yml
Remove the `autorelease: pending` and add `autorelease: tagged`
> chore: Tidy up the PR labels

- .github/workflows/release_please.yml
I think because the condition has a `:` in it we need a multiline string
> chore: Update release_please.yml

- charts/platform/README.md
> chore: Fix release to 0.3.0

- charts/platform/Chart.lock
- charts/platform/Chart.yaml
- charts/platform/README.md
- charts/platform/templates/deployments.yaml
- charts/platform/values.yaml
refs: https://github.com/cloudquery/cloudquery-issues/issues/2900
> feat: Remove redis from Chart

- .github/renovate.json5
- .release-please-manifest.json
- release-please-config.json
Adds operator chart to release please configuration and renovate
> chore: Adding operator chart to CI/CD

- charts/platform/templates/configmap.tpl
Set this to 1minute to increase the refresh rate
> fix: Update `CQAPI_ASSETVIEW_INTERVAL`

- charts/platform/templates/configmap-init-scripts.yaml
`assets` db wasn't getting created. Fixed the script and verified creation.
> chore: Fix clickhouse init script

- charts/platform/templates/configmap.tpl
refs: https://github.com/cloudquery/cloud/pull/4374
> fix: Allow otel collector to be configured

- charts/platform/config/otel-config.yaml
Manual sync due to failing GHA (will look into that later).
> fix: Manually update the otel config

- charts/platform/templates/configmap-init-scripts.yaml
Currently the check is passing incorrectly due to extra data being stored.
> fix: Better handling of determining database existence

- charts/platform/ci/test-values.yaml
- charts/platform/templates/deployments.yaml
- charts/platform/templates/secrets.yaml
- charts/platform/values.yaml
Adds environment variables needed to send events to Rudderstack.
> feat: Add environment variables for analytics events

- charts/platform/templates/configmap.tpl
> fix: Set configmap variables correctly

- charts/platform/templates/configmap.tpl
- charts/platform/values.yaml
This is to match https://github.com/cloudquery/cloud/pull/4843
> fix: Switch to using queue URL instead

- charts/cloudquery/templates/cronjob.yaml
- charts/cloudquery/values.yaml
Follow up to https://github.com/cloudquery/helm-charts/pull/788
> feat: Add ttlSecondsAfterFinished to cron as well
