- .github/workflows/bump_versions.yml
- .github/workflows/ok_to_bump_version.yml
This should allow us to comment on PRs such https://github.com/cloudquery/helm-charts/pull/92 with `/bump sha=<sha>` to add another commit that updates the version and docs
> chore(ci): Add OK to bump workflow

- .github/renovate.json5
This ensures we update chart version and docs after dep updates such as https://github.com/cloudquery/helm-charts/pull/90
> chore: Update chart version on dep updates

- .github/renovate.json5
Follow up to https://github.com/cloudquery/helm-charts/pull/95.
`postUpgradeTasks` should be the same, but `extractVersion` is only for the CLI (CloudQuery)
> chore: Fix renovate config

- .github/renovate.json5
Non CloudQuery dependencies should follow the default schedule
> chore: Only update CloudQuery CLI immediately

- .github/renovate.json5
Our default for regex managers is `chore` but in case of the CLI it should be `fix`
> chore: Use `fix` commit type when updating CloudQuery

- .github/workflows/manual_triggers.yml
Docs say one thing, but logs show another thing:
https://github.com/cloudquery/helm-charts/actions/runs/3088658202/jobs/4995394315#step:3:29
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch:
> chore: Use action instead of event_type

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/admin-deployment.yaml
- charts/cloudquery/templates/cronjob.yaml
- charts/cloudquery/templates/secret.yaml
- charts/cloudquery/values.yaml
Currently the helm chart always creates the secret with the sensible environment variables, even if the `envRenderSecret` is empty. It will create a secret without any value. If after the creation of the secret someone wants to add an environment variable to the secret manually, to avoid commit sensitive values to git, it will create a drift with the original manifest of the secret. 
This PR is just to avoid those cases when you add the secret manually.
> feat: Allow to choose whether to create the secret

- .github/renovate.json5
This is required since we use a tag structure of `cli-v` instead of `cli/v` now
> chore: Fix renovate configuration

- .github/renovate.json5
To be merged after https://github.com/cloudquery/helm-charts/pull/117, so renovate updates CLI, AWS plugin and PostgresSQL plugin in the chart
> chore(deps): Configure renovate to update plugin versions

- .github/renovate.json5
For the plugins we need the full version (for the CLI we use "loose" version matching https://github.com/cloudquery/helm-charts/blob/b085177a6f969ecd14b6091ac004a0e15d2fd603/.github/renovate.json5#L9, https://github.com/cloudquery/helm-charts/blob/b085177a6f969ecd14b6091ac004a0e15d2fd603/charts/cloudquery/Chart.yaml#L26)
> chore(deps): Fix renovate config

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/_helpers.tpl
- charts/cloudquery/templates/admin-deployment.yaml
- charts/cloudquery/templates/cronjob.yaml
- charts/cloudquery/values.yaml
Adding a few more options for the helm chart
- additional labels & annotations (includes making the use of labels more consistent)
- use the specified security context (includes some changes to the security contexts so they work)
- ability to pass extra args to the cron job
It should be possible to go a bit further with locking down the securityContexts in a later PR.  Specifically it should be possible to enable `runAsNonRoot`.  Right now that doesn't work because the `/app` directory permissions in the docker image mean you have to run as root.
> feat: Add more options for helm chart - labels, annotations. securityContexts & cronjob arguments

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
https://github.com/cloudquery/helm-charts/releases/tag/cloudquery-4.0.5 should have been v5 due to the major bump in AWS plugin https://github.com/cloudquery/helm-charts/pull/199
> fix: Bump chart to v5

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/cronjob.yaml
- charts/cloudquery/values.yaml
Wanted to add the ability to configure the [cronJob history limits](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits) for the CloudQuery jobs running in kubernetes to have more control over retaining pod history, runtimes, logs, etc..
I chose names for the variables that hopefully reflect what the option is supposed to configure but I can't say I'm 100% in love with the names either 😬. Open to suggestions on better variable names.
- Added `cronJobLimit` and `cronJobFailedJobsLimit`
- Added defaults for the two new variables.
- Bumped chart version to `5.1.0` as I believe this to be a minor change
- Updated `README` using `make generate-docs`
> feat: Add CronJob History Limits

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/admin-deployment.yaml
- charts/cloudquery/templates/configmap.yaml
- charts/cloudquery/templates/cronjob.yaml
- charts/cloudquery/templates/secret.yaml
- charts/cloudquery/templates/serviceaccount.yaml
- charts/cloudquery/values.yaml
Hi,
I would like to add some improvements to the helm chart. On request, I can split them as well.
1. I added podLabels and serviceAccount labels, since unlike AWS IRSA, Azure Workload Identity depend on them
2. I add a toggle to conditionally enable the admin deployment, since it feels like the deployment is only required for debugging scnarios.
3. I added a toggle to pass config and envRenderSecret trough helm tpl function. This allow umbrella charts to aggregate configuration. In this scenario, I could re-use the [postgresql](https://github.com/bitnami/charts/blob/f4f18c3de0c4103ea2f054d9e2afce1d9ac6919a/bitnami/postgresql/values.yaml#L4-L32) chart values in the cloudquery chart.
4. Fixed the `serviceAccount.autoMount` toggle
> feat: Implement tplConfig and Azure Workload Identity support

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/secret.yaml
Fixes https://github.com/cloudquery/helm-charts/issues/278
Follow up to https://github.com/cloudquery/helm-charts/pull/263.
Since we range over `.Values.envRenderSecret` we need to extract the `tplConfig` before, otherwise we're at the wrong scope
> fix: Fix `tplConfig` scope in `secret.yaml`

- charts/cloudquery/Chart.yaml
- charts/cloudquery/README.md
- charts/cloudquery/templates/admin-deployment.yaml
- charts/cloudquery/templates/cronjob.yaml
- charts/cloudquery/templates/job.yaml
When adopting pre-existing serviceAccounts, the previous evaluation would result in either no service account being included or the existing service account being overridden (if you set `serviceAccount.enabled = "true"`).
This modification enables you to use existing `serviceAccounts` safely (for example, if you created one with `eksctl`).
> fix: Support existing serviceAccount without overwriting

- .github/workflows/deps_bump_versions.yml
We intend to introduce release-please to support the platform helm chart release, as such we do not need to trigger the bump command for platform-only changes.
> chore: Ignore platform helm chart changes in workflow

- .github/workflows/auto_update_docs.yml
Otherwise the new commit doesn't trigger any workflows
> chore: Use a personal access token when updating docs

- .github/workflows/lint_test.yml
- Makefile
This will call the `ct lint` but will skip any version increment checks. This is beacuse the version incrementing only happens as part of the release PR.
> chore: Add a `lint-pr` step

- .github/workflows/release_please.yml
The `release_created` output appears to be only for root component releases - see [docs](https://github.com/googleapis/release-please-action?tab=readme-ov-file#outputs)
> chore: Uses `releases_created`

- .github/workflows/release_please.yml
As part of the release of the platform helmchart, we need to add the bitnamic helm repo dependency.
> chore: Adding bitnami helm dependency

- CODEOWNERS
This will allow the `cloudquery-backend` team to merge platform helm changes.
> chore: Add `cloudquery-backend` codeowners of platform helm chart

- charts/platform/Chart.yaml
- charts/platform/templates/deployments.yaml
- charts/platform/templates/secrets.yaml
Requires the AES encrypted key produced by the init container to be shared with the main container
> fix: Update `appVersion` to 0.15.1

- .github/workflows/auto_update_docs.yml
Otherwise release PRs might have docs from the other chart https://github.com/cloudquery/helm-charts/pull/500
> chore: Update docs for only relevant chart based on branch

- charts/platform/Chart.yaml
- charts/platform/README.md
- charts/platform/templates/deployments.yaml
- charts/platform/templates/secrets.yaml
- charts/platform/values.yaml
This update no longer needs the init container, so removing this and setting the correct environment variables.
Refs: https://github.com/cloudquery/helm-charts/pull/517
> fix!: Update cloud dependency to `v0.23.0`

- charts/platform/templates/deployments.yaml
This is to fix the incoming `cloud` container upgrade where the container now runs as a non-root user
Refs: https://github.com/cloudquery/helm-charts/pull/527
> fix: Use a shared volume for the `CQAPI_LOCAL_AES_KEY_FILE`

- .github/workflows/lint_test.yml
Try updating the Python version - the one we have configured is no [longer supported](https://github.com/cloudquery/helm-charts/actions/runs/12843508016/job/35815536639?pr=552)
> chore: Fix python version

- charts/platform/config/otel-config.yaml
- charts/platform/templates/otelcollector.yaml
This needs to be configurable and derivable from the main ClickHouse DSN (as I think otel and data live in the same DB/schema).
I will fix the todo in a follow-up so that we can unblock the failing PRs.
> fix: Add CLICKHOUSE_DATABASE back to config

- charts/platform/templates/otelcollector.yaml
`env` section already declared, this isn't needed.
> fix: Cleanup extra env variable

- charts/platform/README.md
- charts/platform/ci/test-values.yaml
- charts/platform/templates/otelcollector.yaml
- charts/platform/values.yaml
Even though we are supplying a full DSN (including the database) the CLICKHOUSE_DATABASE variable also needs to be defined.
I've set this to be `default` (by default) which corresponds to a CH database that has been created with no dedicated database (e.g. assets).
We might also look into parsing the DSN in Helm (and CloudFormation) to deduce the value for the CLICKHOUSE_DATABASE.
> fix: Make otel DB configurable

- charts/operator/.helmignore
- charts/operator/Chart.yaml
- charts/operator/README.md
- charts/operator/README.md.gotmpl
- charts/operator/crds/scheduling.cloudquery.io_connectiontests.yaml
- charts/operator/crds/scheduling.cloudquery.io_syncs.yaml
- charts/operator/templates/NOTES.txt
- charts/operator/templates/_helpers.tpl
- charts/operator/templates/deployment.yaml
- charts/operator/templates/role-api.yaml
- charts/operator/templates/role-bindings.yaml
- charts/operator/templates/role-manager.yaml
- charts/operator/templates/service.yaml
- charts/operator/templates/serviceaccount.yaml
- charts/operator/values.yaml
- charts/platform/README.md
- charts/platform/values.yaml
This PR introduces a Helm chart that deploys a platform scheduler as a Kubernetes operator.
By default, the scheduler is automatically detected by the platform and serves as its scheduling backend. For custom configurations, the chart provides the necessary configuration section as output.
```
Operator release `scheduler/2` has been installed!
.--.
.-(    ).    Happy CloudQuery-ing!
(___.__)__)
---
scheduler:
address: scheduler-operator.cloudquery:3001
---
Alternatively, you can append the --set flag to your Helm command:
helm install <params> --set "scheduler.address=scheduler-operator.cloudquery:3001"
```
> feat: Add operator helm chart

- charts/platform/README.md
- charts/platform/templates/deployments.yaml
- charts/platform/templates/pvc.yaml
- charts/platform/templates/storageclass.yaml
- charts/platform/values.yaml
Adding a persistent volume to allow the mirrored plugins to be stored.
- In addition, store the `CQAPI_LOCAL_AES_KEY_FILE` in the persistent volume
- Removed `readOnlyRootFilesystem` value from the pod-level spec (only needs to be in the container)
> feat: Adding persistent volume

- charts/operator/Chart.yaml
- charts/operator/templates/deployment.yaml
This makes the version update compatible with the renovate regex already used in the platform chart: see https://github.com/cloudquery/helm-charts/pull/599
> fix: Prepend `v` to the image tag

- .github/workflows/lint_test.yml
- charts/platform/templates/_helpers.tpl
- charts/platform/templates/configmap.tpl
- charts/platform/templates/deployments.yaml
Add Clickhouse database initialization via init container
This PR adds a database initialization step for Clickhouse using an init container that:
- Parses the Clickhouse DSN from external secrets
- Checks if the target database exists
- Creates the database if it doesn't exist
- Uses curlimages/curl:8.5.0 for minimal footprint
> feat: Add init container to check and create database if missing

- charts/platform/templates/pdb.yaml
- charts/platform/values.yaml
The EKS cluster we are using is configured as an EKS auto cluster. This results in nodes being auto-provisioned whenever pods exceed the available resources. This happens when a sync is triggered, which can lead to the platform and otel-collector pods being re-scheduled onto the new node.
This PR adds Pod Disruption Budgets to ensure that both the platform and otel-collector pods are not interrupted when node scaling occurs. This will likely result in the original node being protected form eviction whilst the sync jobs will be scheduled on a new, bigger node.
> feat: Adding pod disruption budget

- charts/platform/Chart.yaml
- charts/platform/templates/configmap.tpl
This will effectively enable key storage and retrieval via Postgres, preventing key re-generation if the platform pod start in a different zone.
Refs: cloudquery/cloud#4207
> fix: Remove AES key file

- charts/platform/templates/configmap.tpl
This is temporary until some further frontend work enables lazy loading for plugins.
> fix: Mirror all plugins by default

- charts/platform/templates/role.yaml
- charts/platform/templates/rolebinding.yaml
- charts/platform/templates/serviceaccount.yaml
- charts/platform/values.yaml
I think the lack of RBAC rules was blocking reading the live log streams.
There is still an issue with logs being persisted to disk.
refs: cloudquery/cloudquery-issues#3321
> fix: Allow platform container to read logs from k8s API

- charts/operator/templates/_helpers.tpl
- charts/operator/values.yaml
This allows the scheduler to be put in a mode that will force syncs to only launch in a nominated namespace.
> fix: Adding the `SCHEDULER_K8S_SYNC_FORCE_NAMESPACE` environment variable

- charts/platform/templates/otelcollector.yaml
- charts/platform/values.yaml
We were missing liveness and readiness checks for the otel-collector, leaving it possible for the container to hang and be non-responsive.
> fix: Add liveness and readiness probes to otel-collector

- charts/operator/Chart.yaml
- charts/platform/Chart.yaml
Manual update to be faster than the renovate cycle.
> fix: Manual update to `1.2.0` cloudquery container

- .github/renovate.json5
This should use the full CLI version in PRs like https://github.com/cloudquery/helm-charts/pull/748
> chore: Fix CLI version update in cloudquery chart

- charts/platform/ci/test-values.yaml
- charts/platform/templates/deployments.yaml
- charts/platform/templates/secrets.yaml
Adds support for first user/password. Required for multi-tenancy setup where user/password will be provided by CloudAPI add stored in SSM.
Note:
Changes depend on PR : https://github.com/cloudquery/cloud-infrastructure/pull/330
> feat: Adds user and password support.

- charts/cloudquery/templates/job.yaml
- charts/cloudquery/values.yaml
It should allow Kubernetes to automatically clean up jobs after a specified period, defaults to 3 days.
> feat: Add ttlSecondsAfterFinished configuration to chart

- charts/cloudquery/README.md
- charts/cloudquery/templates/_helpers.tpl
- charts/cloudquery/templates/clusterrole.yaml
- charts/cloudquery/templates/clusterrolebinding.yaml
- charts/cloudquery/values.yaml
This PR adds some basic support for RBAC as documented here: https://hub.cloudquery.io/plugins/source/cloudquery/k8s/latest/docs#kubernetes-service-account
Given that a kubernetes deployment of `cloudquery` can't really work without a corresponding role, it might be useful to include it.
The feature is off by default (`rbac.create = false`). And should continue to produce the previous configuration unless the user wants the rbac functionality turned on.
I went ahead and version-bumped the `Chart.yaml` file. Not sure if that's required, or handled by CI. Please let me know if I need to make any changes.
> feat: Add support for rbac resources
